### ISSUE TITLE
Content line could not be parsed into parts Exception

### ISSUE THREAD

**Issue by rchrd2** [collective/icalendar#104]
Is there any way to ignore offending entries and parse the rest of the file? 

Without any icalendar repair tools, it is difficult to read a broken file. 

I tried repairing the file with this regex, but it does not work still:

```
    asciidata = re.sub(r'^(?!([A-Z]+):)', r'     ', asciidata, count=0, flags=re.MULTILINE)

    try:
        cal = icalendar.Calendar.from_ical(asciidata)
    except Exception as detail:
        print >>sys.stderr, detail
```

When the exception is thrown, it prevents the rest of the file from being parsed.

Thank you.

**Comment by potuz** [comment]
I am hitting the same error on a valid V4.0 vcard (using khal to extract bdays)

```
debug: Updating 0a9acecd6abeb4db248c933231cecfc8e4939c315cbe38bd4e7c1a952df690eb.vcf because 1498507884569668096.000000000 != None
debug: Updating b7vf5c4ge3a33le3rr8o4ubor7dl3wzs7byn.vcf because 1498518463768040960.000000000 != None
Unknown exception happened.
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/icalendar/parser.py", line 230, in from_ical
    key, val = q_split(param, '=')
ValueError: need more than 1 value to unpack

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/icalendar/parser.py", line 336, in parts
    strict=self.strict)
  File "/usr/lib64/python3.4/site-packages/icalendar/parser.py", line 255, in from_ical
    % (param, exc))
ValueError: 'data' is not a valid parameter string: need more than 1 value to unpack

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/khal/khalendar/khalendar.py", line 303, in _update_vevent
    update(event.raw, href=href, etag=etag, calendar=calendar)
  File "/usr/lib64/python3.4/site-packages/khal/khalendar/backend.py", line 276, in update_birthday
    ical = icalendar.Event.from_ical(vevent)
  File "/usr/lib64/python3.4/site-packages/icalendar/cal.py", line 324, in from_ical
    name, params, vals = line.parts()
  File "/usr/lib64/python3.4/site-packages/icalendar/parser.py", line 346, in parts
    % (self, exc)
ValueError: Content line could not be parsed into parts: 'PHOTO;data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAsICAoIBwsKCQoNDAsNERwSEQ8PESIZGhQcKSQrKigkJyctMkA3LTA9MCcnOEw5PUNFSElIKzZPVU5GVEBHSEX/2wBDAQwNDREPESESEiFFLicuR....B0bAx696cZITQ9w0q2M8RLeUeXUYHB7/hmpfssf2+do9oUBvlA9RTdKKm1uIZAeCevrTLe5kN9tbgGPb83QEcUXZFz//Z': 'data' is not a valid parameter string: need more than 1 value to unpack
warning: This event will not be available in khal.
```

And the offending vcard is 
```
BEGIN:VCARD
VERSION:4.0
UID:b7vf5c4ge3a33le3rr8o4ubor7dl3wzs7byn
EMAIL;TYPE=home:test@email.net
FN:FirstName Test
N:Test;FirstName;;;
REV:20170626T194129Z
PHOTO;data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAsICAoIBwsKCQoNDAsNERwSEQ8PESIZGhQcKSQrKigk....
END:VCARD
```
