### ISSUE TITLE
cannot import name Calendar

### ISSUE THREAD

**Issue by hkalexling** [collective/icalendar#177]
I followed the installation guild and I tried to import Calendar using

```python
from icalendar import Calendar, Event
```

Then I got the error 

```
Traceback (most recent call last):
  File "calendar.py", line 1, in <module>
    from icalendar import Calendar, Event
  File "/Library/Python/2.7/site-packages/icalendar-3.9.1-py2.7.egg/icalendar/__init__.py", line 1, in <module>
    from icalendar.cal import (
  File "/Library/Python/2.7/site-packages/icalendar-3.9.1-py2.7.egg/icalendar/cal.py", line 20, in <module>
    import dateutil.rrule
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.py", line 12, in <module>
    import calendar
  File "/Users/alex_ling/Desktop/calendar.py", line 1, in <module>
    from icalendar import Calendar, Event
ImportError: cannot import name Calendar
```

I've also tried doing `python -c 'import icalendar'` in terminal, but I got a similar error

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/icalendar-3.9.1-py2.7.egg/icalendar/__init__.py", line 1, in <module>
    from icalendar.cal import (
  File "/Library/Python/2.7/site-packages/icalendar-3.9.1-py2.7.egg/icalendar/cal.py", line 20, in <module>
    import dateutil.rrule
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.py", line 12, in <module>
    import calendar
  File "calendar.py", line 1, in <module>
    from icalendar import Calendar, Event
```

Did I miss something? Thanks in advance.

**Comment by kfdm** [comment]
There's a default python2 module called calendar ( https://docs.python.org/2/library/calendar.html ) so the imports are likely getting confused there. Try renaming your script from calendar.py to something else and run it again.

**Comment by hkalexling** [comment]
Oops stupid me, that's exactly the problem. Thanks man :)
