### ISSUE TITLE
UnicodeEncodeError if TZID parameter is non-ascii

### ISSUE THREAD

**Issue by clivest** [collective/icalendar#237]
```python
# -*- coding: utf-8 -*-
from icalendar import Calendar
from datetime import datetime
import pytz

ics = u"""BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:(UTC-03:00) Brasília
BEGIN:STANDARD
DTSTART:16010101T235959
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=3SA;BYMONTH=2
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T235959
TZOFFSETFROM:-0300
TZOFFSETTO:-0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SA;BYMONTH=10
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ORGANIZER:MAILTO:b@example.com
ATTENDEE:MAILTO:a@example.com
DESCRIPTION;LANGUAGE=pt-BR:something something
UID:something
SUMMARY;LANGUAGE=pt-BR:Something
DTSTART;TZID=\"(UTC-03:00) Brasília\":20170511T133000
DTEND;TZID=\"(UTC-03:00) Brasília\":20170511T140000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20170509T131359Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
END:VEVENT
END:VCALENDAR"""

cal = Calendar.from_ical(ics)
dtstart = cal.walk(name='VEVENT')[0].decoded("DTSTART")
expected = pytz.timezone('America/Sao_Paulo').localize(datetime(2017, 5, 11, 13, 30))
assert dtstart == expected
```

Currently fails with an error due to the timezone TZID parameter having a non-ASCII character:
```
Traceback (most recent call last):
  File "/tmp/t.py", line 42, in <module>
    cal = Calendar.from_ical(tz)
  File "/usr/lib/python2.7/site-packages/icalendar/cal.py", line 347, in from_ical
    _timezone_cache[component['TZID']] = component.to_tz()
  File "/usr/lib/python2.7/site-packages/icalendar/cal.py", line 555, in to_tz
    zone = str(self['TZID'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 16: ordinal not in range(128)
```

I think the ICS in question is valid. RFC5545 defines the TZID value as `paramtext` which includes non-ascii characters.

To fix, I think it's sufficient to do `zone = self['TZID'].encode('ascii', 'replace')` in `Timezone.to_tz()`. zone is used as the timezone name and the name of the `DstTzInfo` subclass. As such it's just informational. The full unicode TZID should continue to be used as the `_timezone_cache` key. I think `tzname = str(component['TZNAME'])` should similarly be fixed. Could also consider using `unicodedata.normalize` to create an ascii version of the TZID string.

What do you think? I'm happy to submit a pull request

**Comment by geier** [comment]
Thank you for reporting this!

I agree, the RFC definitively allows this, the current behavior is a bug and should be fixed.

And yes, your suggestion should work fine and a PR would be appreciated.
