### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by yjs990427** [collective/icalendar#254]
I was trying to parse my ics file but the error on the title happens... and I have no idea why this error is happening...

My code:
```python
import sys
from icalendar import Calendar

icalfile = open("portal.ics")

cal = Calendar(icalfile.read())

print(cal)
```

Traceback:
```
Traceback (most recent call last):
  File "portal.py", line 6, in <module>
    cal = Calendar(icalfile.read())
  File "/home/patrick/.local/lib/python3.6/site-packages/icalendar/cal.py", line 82, in __init__
    super(Component, self).__init__(*args, **kwargs)
  File "/home/patrick/.local/lib/python3.6/site-packages/icalendar/caselessdict.py", line 33, in __init__
    super(CaselessDict, self).__init__(*args, **kwargs)
ValueError: need more than 1 value to unpack
```
My ics file:
[portal.txt](https://github.com/collective/icalendar/files/1601902/portal.txt)

**Comment by azrdev** [comment]
Seems like `class Calendar` has no constructor usable like that, you have to construct the object first, then load your file:
~~~
c = Calendar()
c.from_ics(icalfile.read())
~~~

correct me if I got it wrong :)
