### ISSUE TITLE
Import error in python 3.7.5

### ISSUE THREAD

**Issue by Liu-Molin** [collective/icalendar#297]
I encountered an import error when I try to run
`from icalendar import Calendar`

And the error arises:
```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import icalendar
  File "/usr/local/lib/python3.7/site-packages/icalendar/__init__.py", line 4, in <module>
    from icalendar.cal import (
  File "/usr/local/lib/python3.7/site-packages/icalendar/cal.py", line 20, in <module>
    import dateutil.rrule
  File "/usr/local/lib/python3.7/site-packages/dateutil/rrule.py", line 10, in <module>
    import calendar
  File "/Users/meow/Documents/Projects/UtilScript/calendar.py", line 12, in <module>
    from icalendar import Calendar
ImportError: cannot import name 'Calendar' from 'icalendar' (/usr/local/lib/python3.7/site-packages/icalendar/__init__.py)
```

Recently I just upgraded my python version from `3.6.5` to `3.7.5`. 
And in my server which runs python '3.6.8', this line of code runs totally fine.

So is it any possibility that the recent version `4.0.4` does not support `3.7.5`?

**Comment by Liu-Molin** [comment]
Woooops.
I think the problem is because I named the script 'calendar.py'
