### ISSUE TITLE
icalendar tool breaks on Python 3.x

### ISSUE THREAD

**Issue by moubctez** [collective/icalendar#316]
While trying `icalendar view invite.ics` I get:
```
Traceback (most recent call last):
  File "/dist/pkg/bin/icalendar-3.8", line 11, in <module>
    load_entry_point('icalendar==4.0.6', 'console_scripts', 'icalendar')()
  File "/dist/pkg/lib/python3.8/site-packages/icalendar/cli.py", line 104, in main
    args.func(**{k: v for k, v in vars(args).items()
  File "/dist/pkg/lib/python3.8/site-packages/icalendar/cli.py", line 65, in view
    output_handle.write(_template.format(
TypeError: write() argument must be str, not bytes
```
Same error for Python 3.6, 3.7, and 3.8, but works correctly with Python 2.7.

**Comment by usonianhorizon** [comment]
I am following up to see if there has been any progress on this?  Under FreeBSD, pip3 installs iCalendar 4.0.9 which outputs a similar error to above:

```
Traceback (most recent call last):
  File "/home/pavneet/.local/bin/icalendar", line 8, in <module>
    sys.exit(main())
  File "/home/pavneet/.local/lib/python3.7/site-packages/icalendar/cli.py", line 104, in main
    args.func(**{k: v for k, v in vars(args).items()
  File "/home/pavneet/.local/lib/python3.7/site-packages/icalendar/cli.py", line 74, in view
    description=event.get('description', '')).encode('utf-8'))
TypeError: write() argument must be str, not bytes
```

advTHANKSance

**Comment by usonianhorizon** [comment]
> TypeError: write() argument must be str, not bytes

After inspecting `event` on line 66 in `cli.py`, which showed the values of the `dict` to be byte objects, e.g., the value causing the error ` 'DESCRIPTION': vText('b'...` I sought to get a quick fix to outputting the formatted event to `stdout`.
 
As per https://stackoverflow.com/a/4290730/1122167 I changed line 65 from:

```
output_handle.write(_template.format(
```

to:

```
        sys.stdout.buffer.write(
            _template.format(
```

I haven't delved too much into what the implication would be for **all** calls to the `view` method, but this solved my immediate problem, which was to decode vCalendar invites I get from the various cloud calendaring systems at the command line.

HTH.  Cheers.

**Comment by Thorbenl** [comment]
@usonianhorizon so this package is not at all usable for us? :D
```python
    feed = feedgenerator.ICal20Feed(
        title="My Events",
        link="http://www.example.com/events.ical",
        description="A iCalendar feed of my events.",
        language="en",
    )
    feed.add_item(
        title="Hello",
        link="http://www.example.com/test/",
        description="Testing.",
        start_datetime=datetime(2012, 5, 6, 10, 00),
        end_datetime=datetime(2012, 5, 6, 11, 00)
    )

    fp = open("test.ics", "w")
    feed.write(fp, "utf-8")
    response = HttpResponse(content_type='text/calendar')
    response['Filename'] = 'filename.ics'  # IE needs this
    response['Content-Disposition'] = 'attachment; filename=filename.ics'
    return response
```

this is kinda weird it does not support python3 lol

**Comment by drzraf** [comment]
Under Python 3.x, removing the `.encode('utf-8')` make it work.
But it's indeed quite a serious problem.

**Comment by niccokunzmann** [comment]
I think, a pull request would be very welcome. It is an open-source project. The fix is easy. Instead of writing a work around in many lines, this can be a one-liner, fixing it for many. Thanks for your investigations!

**Comment by niccokunzmann** [comment]
@jacadzaca would you consider this closable?
Is there an example ICS file to test that with?
Who would like a next release, soon?

**Comment by jacadzaca** [comment]
I ran the cli tool on [this sample file](https://raw.githubusercontent.com/nik9839/test/master/invite.ics) using python3.10 and python3.8, it worked as intended. The issue's solved in my book

**Comment by niccokunzmann** [comment]
Yep, can be closed, now:

```
sabin@schneidebrett:~/icalendar$ git checkout 77d071be47fc6f1621d8cf40d5012b47f905807c
Note: switching to '77d071be47fc6f1621d8cf40d5012b47f905807c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 77d071b Merge pull request #306 from tuergeist/fix-deprecated
sabin@schneidebrett:~/icalendar$ .tox/py39/bin/python -m icalendar.cli view invite.ics 
Traceback (most recent call last):
  File "/home/sabin/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/runpy.py", line 200, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sabin/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sabin/icalendar/src/icalendar/cli.py", line 109, in <module>
    main()
  File "/home/sabin/icalendar/src/icalendar/cli.py", line 102, in main
    args.func(**{k: v for k, v in vars(args).items()
  File "/home/sabin/icalendar/src/icalendar/cli.py", line 63, in view
    output_handle.write(_template.format(
TypeError: unicode argument expected, got 'bytes'
sabin@schneidebrett:~/icalendar$ git checkout -b issue-^C
sabin@schneidebrett:~/icalendar$ git checkout master
Previous HEAD position was 77d071b Merge pull request #306 from tuergeist/fix-deprecated
Switched to branch 'master'
Your branch is up to date with 'upstream/master'.
sabin@schneidebrett:~/icalendar$ .tox/py39/bin/python -m icalendar.cli invite.ics 
    Organizer: nikhil.gupta <nikhil.gupta@veris.in>
    Attendees:
     nikhilgupta709 <nikhilgupta709@gmail.com>
     nikhil.gupta <nikhil.gupta@veris.in>
    Summary    : sample event
    Starts     : Wed Nov 20 16:00:00 2019
    End        : Wed Nov 20 17:00:00 2019
    Duration   : 1:00:00
    Location   : 
    Comment    : 
    Description:
     -::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-
     Please do not edit this section of the description.
     
     View your event at https://www.google.com/calendar/event?action=VIEW&eid=MHNibmNpcHVtYmI5NHFwam8wMjFvcmQ1b2UgbmlraGlsZ3VwdGE3MDlAbQ&tok=MjEjbmlraGlsLmd1cHRhQHZlcmlzLmluOTFhMjQ1OTVlNDk4MTZkYTVkNWM3NDRlY2M2ODQ5Zjk0NjQ4YjJhZQ&ctz=Asia%2FKolkata&hl=en&es=1.
     -::~:~::~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~:~::~:~::-

```
