### ISSUE TITLE
dst_offset is not False

### ISSUE THREAD

**Issue by monofox** [collective/icalendar#321]
Hi,

Figured out following issue on icalendar 4.0.7 from pypi.

ICS file:
```ics
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//PIMUTILS.ORG//NONSGML khal / icalendar //EN
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
DTSTART;VALUE=DATE-TIME:20200329T030000
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY:Reifenwechsel
DTSTART;TZID=Europe/Berlin;VALUE=DATE-TIME:20200403T102000
DTEND;TZID=Europe/Berlin;VALUE=DATE-TIME:20200403T113000
DTSTAMP;VALUE=DATE-TIME:20200326T165608Z
UID:TCK6EMQBQHQ8KB4PDQPT04Q7HBYNS2MEPZMO
SEQUENCE:0
LOCATION:Musterhausen
END:VEVENT
END:VCALENDAR
```

Results in:
```
Traceback (most recent call last):
  File "~/calreminder/calreminder.py", line 10, in <module>
    events += icalevents.icalevents.events(url=None, file=evtFile, string_content=None, fix_apple=True)
  File "~/.local/lib/python3.8/site-packages/icalevents/icalevents.py", line 50, in events
    found_events += parse_events(content, start=start, end=end)
  File "~/.local/lib/python3.8/site-packages/icalevents/icalparser.py", line 259, in parse_events
    timezones[name] = c.to_tz()
  File "~/.local/lib/python3.8/site-packages/icalendar/cal.py", line 650, in to_tz
    assert dst_offset is not False
AssertionError
```

As you can see, the file was generated by khal (some days ago...).

Event was on 03.04.2020 at 10:20 am to 11:30 am CEST (summer time). File/Event was created on 26.03.2020 at 4:30 pm CET (normal time). 

Is it right to open here or must this be handled by icalevents? Its reproducible if the same statements are done directly with icalendar.

Thanks and best regards,
Lukas

**Comment by monofox** [comment]
It is failing with `master` branch with an `AssertionError` i do not expect. I would expect, that it is parseable.
And i still can reproduce:

```python
#!/usr/bin/env python3
import icalendar

ics = """BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//PIMUTILS.ORG//NONSGML khal / icalendar //EN
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
DTSTART;VALUE=DATE-TIME:20200329T030000
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY:Reifenwechsel
DTSTART;TZID=Europe/Berlin;VALUE=DATE-TIME:20200403T102000
DTEND;TZID=Europe/Berlin;VALUE=DATE-TIME:20200403T113000
DTSTAMP;VALUE=DATE-TIME:20200326T165608Z
UID:TCK6EMQBQHQ8KB4PDQPT04Q7HBYNS2MEPZMO
SEQUENCE:0
LOCATION:Musterhausen
END:VEVENT
END:VCALENDAR
"""
cal = icalendar.Calendar.from_ical(ics)
timezone = list(cal.walk())[1]
print(timezone)
pytz = timezone.to_tz()
```

According to the description - to_tz should "convert this VTIMEZONE component to a pytz.timezone object". Instead its throwing assert error.

Event was generated by `khal`.

**Comment by niccokunzmann** [comment]
Awesome! #379 can reproduce the error! PR for a fix to that branch is welcome!
