### ISSUE TITLE
Fail when run with no arguments

### ISSUE THREAD

**Issue by drzraf** [collective/icalendar#353]
```
$ icalendar 
Traceback (most recent call last):
  File "/home/x/.local/bin/icalendar", line 8, in <module>
    sys.exit(main())
  File "/home/x/.local/lib/python3.8/site-packages/icalendar/cli.py", line 104, in main
    args.func(**{k: v for k, v in vars(args).items()
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by jacadzaca** [comment]
@niccokunzmann I think pull requests #324 also fixes this issue

**Comment by niccokunzmann** [comment]
```
~/icalendar$ .tox/py39/bin/python -m icalendar.cli
usage: cli.py [-h] [--output OUTPUT] [-v] calendar_files [calendar_files ...]
cli.py: error: the following arguments are required: calendar_files
```
Correct! Thanks @jacadzaca
