### ISSUE TITLE
[REGRESSION] DDDType not hashable in icalendar 5

### ISSUE THREAD

**Issue by tobixen** [collective/icalendar#487]
Compare this:

```
>>> import icalendar
>>> import datetime
>>> icalendar.__version__
'4.0.9'
>>> icalendar.vDDDTypes(datetime(2022,10,10)).__hash__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
>>> icalendar.vDDDTypes(datetime.datetime(2022,10,10)).__hash__()
8729746249635
>>> icalendar.vDDDTypes(datetime.datetime(2022,10,10)).__hash__
<method-wrapper '__hash__' of vDDDTypes object at 0x7f08d6c97cd0>
>>>
```

with this:

```
>>> import icalendar
>>> import datetime
>>> icalendar.__version__
'5.0.1'
>>> icalendar.vDDDTypes(datetime.datetime(2022,10,10)).__hash__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not callable
>>> icalendar.vDDDTypes(datetime.datetime(2022,10,10)).__hash__
```

I noticed tests failing because of this in another project - https://github.com/niccokunzmann/python-recurring-ical-events/issues/99

**Comment by niccokunzmann** [comment]
Hm. It should be possible to add `__hash__` and `__eq__`. I wonder where it was removed.

**Comment by jacadzaca** [comment]
I couldn't find a commit where `__hash__` would be removed from vDDDTypes class, but `__hash__` might have disappeared due #391. In [python3 every class that overrides `__eq__` has `__hash__` set to None](https://docs.python.org/3/reference/datamodel.html#object.__hash__) if no custom implementation of it is provided.

**Comment by jacadzaca** [comment]
We've disscused implementing `vDDDTypes.__hash__` [here](https://github.com/collective/icalendar/pull/391#discussion_r957476223).

**Comment by niccokunzmann** [comment]
Thanks for the research!

**Comment by niccokunzmann** [comment]
I'll give it a go.

**Comment by niccokunzmann** [comment]
Fixed in v5.0.3.
