### ISSUE TITLE
[BUG] Coveralls does not report coverage

### ISSUE THREAD

**Issue by niccokunzmann** [collective/icalendar#677]
## Describe the bug

Coveralls is supposed to generate a pull request summary. Currently, it breaks on `main` and on the pull requests.

## To Reproduce

See `main` and the commits:

https://github.com/collective/icalendar/actions/runs/9751261758/job/26912463324#step:6:1

```
Error running coveralls: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
Received 422 submitting job via Github Actions. By default, coveralls-python uses the "github" service name, which requires you to set the $GITHUB_TOKEN environment variable. If you want to use a COVERALLS_REPO_TOKEN instead, please manually override $COVERALLS_SERVICE_NAME to "github-actions". For more info, see https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/coveralls/api.py", line 298, in submit_report
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/coveralls/cli.py", line 98, in main
    result = coverallz.wear()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/coveralls/api.py", line 275, in wear
    return self.submit_report(json_string)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/coveralls/api.py", line 301, in submit_report
    raise CoverallsException(
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
/opt/hostedtoolcache/Python/3.8.18/x64/bin/coveralls
```

## Expected behavior

I would like coveralls to
- [ ] run during PR and `main` builds
- [ ] provide a comment as it did before about the test coverage

## Additional context

- #644 
- #664

**Comment by niccokunzmann** [comment]
coveralls is reporting coverage. https://github.com/collective/icalendar/pull/680#issuecomment-2204296199

**Comment by niccokunzmann** [comment]
This re-occurs on pull-requests from outsiders.

**Comment by niccokunzmann** [comment]
This seems to work now.
