### ISSUE TITLE
failing to parse a VEVENT with embedded HTML

### ISSUE THREAD

**Issue by rbpasker** [collective/icalendar#84]
here's a small program copied from the docs:

``` python
from icalendar import Calendar, Event
from datetime import datetime
import pprint

calfile = '/Users/rbp/Downloads/calendar.ical'
cal = Calendar.from_ical(open(calfile,'rb').read())
for component in cal.walk():
    pprint.pprint(component)
```

it breaks on a VEVENT that has embedded HTML. this violates RFC 2445 4.1, for sure.  but it seems that Calendar on both OS/X 10.8 and IOS 6 both accept it.

```
 Traceback (most recent call last):
  File "tengah/workers/ical/icalworker.py", line 7, in <module>
    cal = Calendar.from_ical(open(calfile,'rb').read())
  File "/Users/rbp/Projects/tengahdb/lib/python2.7/site-packages/icalendar/cal.py", line 412, in from_ical
   name, params, vals = line.parts()
  File "/Users/rbp/Projects/tengahdb/lib/python2.7/site-packages/icalendar/parser.py", line 526, in parts
    raise ValueError, "Content line could not be parsed into parts: %r: %s" % (self, e)
ValueError: Content line could not be parsed into parts: '<P DIR=LTR><SPAN LANG="en-us"></SPAN><SPAN LANG="en-us"><FONT FACE="Calibri">Silicon Valley Venture CONNECT:NYC</FONT></SPAN></P>': <P DIR=LTR><SPAN LANG="en-us"></SPAN><SPAN LANG="en-us"><FONT FACE="Calibri">Silicon Valley Venture CONNECT
```

here is the event which has the embedded HTML. Looks like there are no spaces in col 1 before the markup

```
BEGIN:VEVENT
SUMMARY:Silicon Valley Venture CONNECT: NYC
PRIORITY:5
CLASS:PUBLIC
<P DIR=LTR><SPAN LANG="en-us"></SPAN><SPAN LANG="en-us"><FONT 
 FACE="Calibri">Silicon Valley Venture CONNECT:NYC</FONT></SPAN></P>
<P DIR=LTR><SPAN LANG="en-us"></SPAN><SPAN LANG="en-us"><FONT 
 FACE="Calibri"></FONT></SPAN><SPAN LANG="en-us"></SPAN><SPAN 
 LANG="en-us"></SPAN><SPAN LANG="en-us">&nbsp:</SPAN></P>
UID:
 040000008200E00074C5B7101A82E0080000000080014D63E6EFCD01000000000000000010
 000000A9040CD0D461274B96FFE0377A232232
DTSTART;TZID=US/Pacific:20130130T150000
SEQUENCE:0
LOCATION:Four Seasons New York (57 East 57th Street)
DTSTAMP:20130116T192905Z
LAST-MODIFIED:20130116T192905Z
CREATED:20130116T192905Z
DTEND;TZID=US/Pacific:20130130T180000
DESCRIPTION:Silicon Valley Venture CONNECT: NYC\n\nWednesday\, January 
 30th\n6 - 9 pm ET\n\nFour Seasons New York\n57 East 57th Street\nNew 
 York\, NY 10022\n \n\n
ATTACH;MANAGED-ID=11e1b05faa;FILENAME=Attachment;
 FMTTYPE=application/octet-stream;SIZE=500209:https:
 //p02-caldav.icloud.com/39941937/attach/2_AFL2YNSD5UD434M3PYAMB3VF6DRYQQQZ
 HDU5UK2FLV7Z72QGJOOF45PMXFGO67IAKJIWMKEYJTD7GECXJQ4RQHGUPW2I6ZNFJ4JWF47UI6
 GCQPQUCIN6QUOCX3ZICVVNWPPZX37ARN2LTCIVUSNNP5VBMYZTBYCKZNAMO42HKCF2JLV5ZAU2
 QMUCGLCJXWZ6XOGVEDMFUUFTI7TWTOTMJ5TKWEXPR7TOTKVWLGI/Attachment
X-ALT-DESC;FMTTYPE=text/html:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 
 3.2//EN">
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but 
 could not find a property name or component begin tag: <HTML>
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but 
 could not find a property name or component begin tag: <HEAD>
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but 
 could not find a property name or component begin tag: <META 
 NAME=\"Generator\" CONTENT=\"MS Exchange Server version 
 14.02.5004.000\">
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but 
 could not find a property name or component begin tag: <TITLE></TITLE>
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but 
 could not find a property name or component begin tag: </HEAD>
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but 
 could not find a property name or component begin tag: <BODY>
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but 
 could not find a property name or component begin tag: <!-- Converted 
 from text/rtf format -->
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but 
 could not find a property name or component begin tag: <P DIR=LTR><SPAN 
 LANG=\"en-us\"><FONT FACE=\"Calibri\">Wednesday\, January 
 30th</FONT></SPAN></P>
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but 
 could not find a property name or component begin tag: <P DIR=LTR><SPAN 
 LANG=\"en-us\"><FONT FACE=\"Calibri\">6 - 9 pm ET</FONT></SPAN></P>
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but 
 could not find a property name or component begin tag: <P DIR=LTR><SPAN 
 LANG=\"en-us\"><FONT FACE=\"Calibri\">Four Seasons New 
 York</FONT></SPAN></P>
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but 
 could not find a property name or component begin tag: <P DIR=LTR><SPAN 
 LANG=\"en-us\"><FONT FACE=\"Calibri\">57 East 57th 
 Street</FONT></SPAN></P>
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but 
 could not find a property name or component begin tag: <P DIR=LTR><SPAN 
 LANG=\"en-us\"><FONT FACE=\"Calibri\">New York\, NY 
 10022</FONT></SPAN></P>
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but 
 could not find a property name or component begin tag: <P DIR=LTR><SPAN 
 LANG=\"en-us\"></SPAN><SPAN LANG=\"en-us\"></SPAN></P>
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but 
 could not find a property name or component begin tag: </BODY>
X-LIC-ERROR;X-LIC-ERRORTYPE=COMPONENT-PARSE-ERROR:Got a data line\, but 
 could not find a property name or component begin tag: </HTML>
X-MS-OLK-AUTOFILLLOCATION:FALSE
X-MS-OLK-CONFTYPE:0
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
TRANSP:OPAQUE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
```

**Comment by untitaker** [comment]
I think this can be closed.

**Comment by geier** [comment]
agree

**Comment by rbpasker** [comment]
why?

**Comment by untitaker** [comment]
Because the ics file is completely invalid.
